#' Returns JPG files generated by the camera
#'
#' @param from A path (character string).
#' @param raw_ext A character string specifying the extension used for RAW files.
#' @param jpg_ext A character string specifying the extension used for JPG files.
#' @return Returns a vector of character strings with the full names of the JPG
#' files that were generated by the camera.
#' @examples
#' # jpg_from_camera()
jpg_from_camera <- function(from = "~/Pictures/Photos/", raw_ext = "ORF", jpg_ext = "JPG") {
  files <- all_files(from, relative = TRUE)
  orfs <- remove_extension(extract_types(files, raw_ext), raw_ext)
  jpgs <- remove_extension(extract_types(files, jpg_ext), jpg_ext)
  paste0(from, jpgs[jpgs %in% orfs], jpg_ext)
}
